# Generated by Django 2.2.1 on 2019-05-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url_slug', models.CharField(default='', max_length=100)),
                ('description', models.TextField(null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('repository', models.CharField(max_length=100)),
                ('languages', models.TextField(null=True)),
                ('stack', models.TextField(null=True)),
                ('hosting', models.CharField(max_length=100, null=True)),
                ('current', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
    ]
