# Generated by Django 2.2.1 on 2019-05-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url_slug', models.CharField(default='', max_length=100)),
                ('description', models.TextField(null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('repository', models.CharField(max_length=100)),
                ('languages', models.TextField(null=True)),
                ('stack', models.TextField(null=True)),
                ('hosting', models.CharField(max_length=100, null=True)),
                ('current', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSpecs',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='specs', serialize=False, to='work.Project')),
                ('technical_summary', models.TextField(default='To be added.', null=True)),
                ('best_features', models.TextField(default='To be added.', null=True)),
                ('future_plans', models.TextField(default='To be added.', null=True)),
                ('things_learned', models.TextField(default='To be added.', null=True)),
                ('preview', models.ImageField(null=True, upload_to='thumbnails')),
                ('header', models.ImageField(null=True, upload_to='headers')),
            ],
        ),
    ]
