# Generated by Django 2.2.1 on 2019-05-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.TextField(null=True),
        ),
    ]
