# Generated by Django 2.2.1 on 2019-05-29 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSpecs',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='specs', serialize=False, to='work.Project')),
                ('technical_summary', models.TextField(null=True)),
                ('best_features', models.TextField(null=True)),
                ('future_plans', models.TextField(null=True)),
                ('things_learned', models.TextField(null=True)),
            ],
        ),
    ]
