# Generated by Django 2.2.1 on 2019-05-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20190529_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspecs',
            name='best_features',
            field=models.TextField(default='To be added.'),
        ),
        migrations.AlterField(
            model_name='projectspecs',
            name='future_plans',
            field=models.TextField(default='To be added.'),
        ),
        migrations.AlterField(
            model_name='projectspecs',
            name='header',
            field=models.ImageField(null=True, upload_to='headers/'),
        ),
        migrations.AlterField(
            model_name='projectspecs',
            name='preview',
            field=models.ImageField(null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='projectspecs',
            name='technical_summary',
            field=models.TextField(default='To be added.'),
        ),
        migrations.AlterField(
            model_name='projectspecs',
            name='things_learned',
            field=models.TextField(default='To be added.'),
        ),
    ]
