# Generated by Django 2.2.1 on 2019-05-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20190509_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url_slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
