# Generated by Django 2.2.1 on 2019-05-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20190530_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspecs',
            name='header',
            field=models.ImageField(default='default.png', upload_to='headers'),
        ),
        migrations.AlterField(
            model_name='projectspecs',
            name='preview',
            field=models.ImageField(default='default.png', upload_to='thumbnails'),
        ),
    ]
