# Generated by Django 2.2.3 on 2019-07-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_project_extra_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='best',
            field=models.BooleanField(default=False),
        ),
    ]
