# Generated by Django 2.2.3 on 2019-07-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_project_best'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='one_line',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
